tap "alecharmon/tap"
tap "arthur-ficial/tap", "https://github.com/Arthur-Ficial/homebrew-tap"
tap "azure/functions"
tap "azure/kubelogin", "https://github.com/Azure/homebrew-kubelogin"
tap "cassettelab/cassette", "https://github.com/CassetteLab/homebrew-cassette", trusted: true
tap "charmbracelet/tap"
tap "cormacrelf/tap"
tap "dagger/tap"
tap "docker/tap"
tap "hashicorp/tap", trusted: true
tap "lognseth/tap"
tap "mattiapun/subtui", "https://github.com/MattiaPun/homebrew-subtui"
tap "moabukar/tap"
tap "nklmilojevic/sofka"
tap "patrik-csak/tap"
tap "stackitcloud/tap"
tap "supersonic-app/supersonic", trusted: true
tap "universal-ctags/universal-ctags"
tap "vanchonlee/tap"
tap "whiteducksoftware/tap"
tap "xykong/tap"
brew "asdf"
brew "awscli"
brew "azure-cli"
brew "bash"
brew "fzf"
brew "gh"
brew "git"
brew "gitleaks"
brew "helm"
brew "helm-ls"
cask "font-jetbrains-mono-nerd-font"
brew "jq"
brew "kubernetes-cli"
brew "kube-ps1"
brew "kubecolor"
brew "kubectx"
brew "argocd"
brew "kubie"
brew "mas"
brew "powershell", link: false
brew "pre-commit"
brew "pv"
brew "s3cmd"
brew "telnet"
brew "terraform-docs"
brew "terraform-ls"
brew "trash"
brew "uv"
brew "wget"
brew "zoxide"
brew "zsh"
brew "azure/kubelogin/kubelogin", trusted: true
brew "lognseth/tap/azenv", trusted: true
cask "docker-desktop"
cask "drawio"
cask "gcloud-cli"
cask "ghostty"
cask "powershell"
cask "docker/tap/sbx"
cask "stackit"
cask "zed"
mas "Azure VPN Client", id: 1553936137
uv "basedpyright"
npm "cline"
npm "pnpm"
